import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

import { Product } from "../types/product";

interface ProductPageProps {
  product: Product;
}

const ProductPage: NextPage<ProductPageProps> = ({ product }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Products Page</h1>

        <p>Add content from figma mocks here</p>

        <div>
          {product.title}
          {product.description}
          <img src={product.image} alt={product.title} />
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<ProductPageProps> = async (
  context
) => {
  const response = await fetch(
    `http://localhost:3000/api/products/${context.query.id}`
  );
  const product = (await response.json()) as Product;

  return {
    props: {
      product,
    },
  };
};

export default ProductPage;
